// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV1ZXfY-vYU45Cw6-_dhAetaGbSpELIME',
    appId: '1:6433175697:web:d7a3cc1844c8220078a730',
    messagingSenderId: '6433175697',
    projectId: 'wasset-2d868',
    authDomain: 'wasset-2d868.firebaseapp.com',
    storageBucket: 'wasset-2d868.firebasestorage.app',
    measurementId: 'G-CQ0SY53NZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUy43xikb18Sb6tSqP58z2UpQbMnR2S4',
    appId: '1:6433175697:android:d7509a7bed9dbb5478a730',
    messagingSenderId: '6433175697',
    projectId: 'wasset-2d868',
    storageBucket: 'wasset-2d868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8LFWlR0BiXiAkBw2dc7O9ckC9wgIgWo',
    appId: '1:6433175697:ios:7a93177379dd9ce878a730',
    messagingSenderId: '6433175697',
    projectId: 'wasset-2d868',
    storageBucket: 'wasset-2d868.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl8LFWlR0BiXiAkBw2dc7O9ckC9wgIgWo',
    appId: '1:6433175697:ios:7a93177379dd9ce878a730',
    messagingSenderId: '6433175697',
    projectId: 'wasset-2d868',
    storageBucket: 'wasset-2d868.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV1ZXfY-vYU45Cw6-_dhAetaGbSpELIME',
    appId: '1:6433175697:web:1bf0e90e93a5578a78a730',
    messagingSenderId: '6433175697',
    projectId: 'wasset-2d868',
    authDomain: 'wasset-2d868.firebaseapp.com',
    storageBucket: 'wasset-2d868.firebasestorage.app',
    measurementId: 'G-RPFEGKK8KJ',
  );
}
